---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - target: 8211
        published: 8211
        protocol: udp
        mode: host
      - target: 27015
        published: 27015
        protocol: udp
        mode: host  # Required if you want your server to show up in the community servers tab
      - target: 25575
        published: 25575
        protocol: tcp
        mode: host  # Required if you want to use RCON
    env_file:
      - .env
    volumes:
      - ./palworld:/palworld/
